spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 10MB
  data:
    web:
      sort:
        sort-parameter: sort
      pageable:
        default-page-size: 20
        size-parameter: size
        page-parameter: page
  datasource:
    hikari:
      jdbc-url: "jdbc:postgresql://localhost:5432/Tails"
      maximum-pool-size: 15
      driver-class-name: org.postgresql.Driver
    username: "${SPRING_DATASOURCE_USERNAME:postgres}"
    password: "${SPRING_DATASOURCE_PASSWORD:1111}"
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/Tails}"
  flyway:
    baseline-on-migrate: true
    baseline-version: 1.003

---
server:
  port: 8080


gcs:
  images:
    pathToGCSJsonCredentials: "service/src/main/resources/rent-platform-storage-395e699267fc.json"
    bucket: rentimages